#
#  ______  ______  ___   ___  ______  ______  ______  ______       
# /_____/\/_____/\/___/\/__/\/_____/\/_____/\/_____/\/_____/\      
# \:::_ \ \::::_\/\::.\ \\ \ \:::_ \ \:::_ \ \::::_\/\:::_ \ \     
#  \:\ \ \ \:\/___/\:: \/_) \ \:\ \ \ \:\ \ \ \:\/___/\:(_) ) )_   
#   \:\ \ \ \::___\/\:. __  ( (\:\ \ \ \:\ \ \ \::___\/\: __ `\ \  
#    \:\/.:| \:\____/\: \ )  \ \\:\_\ \ \:\/.:| \:\____/\ \ `\ \ \ 
#     \____/_/\_____\/\__\/\__\/ \_____\/\____/_/\_____\/\_\/ \_\/ 
#                                                                 
#
#   If you have downloaded the source code for "Small World Deluxe" and are reading this,
#   then thank you from the bottom of our hearts for making use of our hard work, sweat
#   and tears in whatever you are implementing this into!
#
#   Copyright (C) 2020 - 2022. GekkoFyre.
#
#   Small World Deluxe is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Small World is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with Small World Deluxe.  If not, see <http://www.gnu.org/licenses/>.
#
#
#   The latest source code updates can be obtained from [ 1 ] below at your
#   discretion. A web-browser or the 'git' application may be required.
#
#   [ 1 ] - https://code.gekkofyre.io/amateur-radio/small-world-deluxe
#

#
# https://gitlab.com/gitlab-org/gitlab-foss/issues/27436
# https://docs.gitlab.com/ee/user/packages/container_registry/
# https://hub.docker.com/r/burningdaylight/docker-mingw-qt5
# https://www.archlinux.org/packages/
#

### --------------------------------------------------------------------------------------------------- ###

# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables

image: code.gekkofyre.io:5050/amateur-radio/small-world-deluxe:latest
stages:
- sworld_debug_archlinux_x86_64
- sworld_sentry_archlinux_x86_64
- test
include:
- template: Jobs/SAST.gitlab-ci.yml
- template: Jobs/Secret-Detection.gitlab-ci.yml
- template: Jobs/Code-Quality.gitlab-ci.yml
variables:
  SAST_DISABLE_DIND: 'true'
  GIT_SUBMODULE_STRATEGY: recursive

code_quality:
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]

### --------------------------------------------------------------------------------------------------- ###

#
# https://code.gekkofyre.io/help/user/application_security/sast/index
#

sworld_debug_archlinux_x86_64:
  stage: sworld_debug_archlinux_x86_64
  image: code.gekkofyre.io:5050/amateur-radio/small-world-deluxe:latest
  before_script:
  - pacman -Sy --noconfirm
  - pacman -Syyu --noconfirm
  - strip --remove-section=.note.ABI-tag /usr/lib64/libQt5Core.so.5
  script:
  - sh bootstrap.sh
  - mkdir -p src_build && cd src_build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ..
  - make -j$(nproc)
  - cd ./..
  after_script:
  - echo "Finished execution of Preparatory Build and secondary, lesser stage!"
  artifacts:
    expire_in: 2 weeks
    paths:
    - src_build/
  when: always

### --------------------------------------------------------------------------------------------------- ###

sworld_sentry_archlinux_x86_64:
  stage: sworld_sentry_archlinux_x86_64
  dependencies:
  - sworld_debug_archlinux_x86_64
  before_script:
  - curl -sL https://sentry.io/get-cli/ | bash
  script:
  - sentry-cli --auth-token $GK_SENTRY_AUTH_KEY --url $GK_SENTRY_URL upload-dif -o
    $GK_SENTRY_ORG -p small-world-deluxe ./src_build/ --include-sources --log-level=error
  - sentry-cli --auth-token $GK_SENTRY_AUTH_KEY releases --org $GK_SENTRY_ORG new $MAJOR.$MINOR.$PATCH --url $GK_SENTRY_URL --project small-world-deluxe
  - sentry-cli --auth-token $GK_SENTRY_AUTH_KEY releases set-commits $MAJOR.$MINOR.$PATCH --auto
  after_script:
  - echo "Finished uploading data to Sentry server!"
  artifacts:
    expire_in: 1 week
    paths:
    - src_build/
  allow_failure: true
